version: '3.1'
services:

    postgres_db:
        container_name: ${POSTGRES_CONTAINER_NAME}
        image: ${POSTGRES_IMAGE}
        restart: always
        environment:
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        ports:
            - ${POSTGRES_PORT}
        expose:
            - ${POSTGRES_EXPOSE}
        volumes:
            - ${POSTGRES_VOLUME}
    
    mongo_db:
        container_name: ${MONGO_CONTAINER_NAME}
        image: ${MONGO_IMAGE}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}
        expose:
            - ${MONGO_EXPOSE}